require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe ControlsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Control. As you add validations to Control, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryBot.build(:control).attributes
  }

  let(:invalid_attributes) {
    { title: 'MyString',
      desc: 'MyString',
      impact: 1.5,
      refs: 'MyString' }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ControlsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  context 'Editor is logged in' do
    let(:user) { FactoryBot.create(:editor) }
    before do
      db_sign_in user
    end

    before(:each) do
      @profile = create :profile, created_by: user
    end

    describe 'GET #show' do
      it 'returns a success response' do
        control = create :control, profile_id: @profile.id, created_by: user
        get :show, params: { profile_id: @profile.id, id: control.to_param }, session: valid_session
        expect(response).to be_success
      end
    end

    describe 'GET #details' do
      it 'returns a success response' do
        control = create :control, profile_id: @profile.id, created_by: user
        get :details, format: 'js', params: { profile_id: control.profile_id, id: control.to_param }, xhr: true, session: valid_session
        expect(response.content_type).to eq('text/javascript')
      end
    end

    describe 'GET #new' do
      it 'returns a success response' do
        get :new, params: { profile_id: @profile.id }, session: valid_session
        expect(response).to be_success
      end
    end

    describe 'GET #edit' do
      it 'returns a success response' do
        control = create :control, profile_id: @profile.id, created_by: user
        get :edit, params: { profile_id: @profile.id, id: control.to_param }, session: valid_session
        expect(response).to be_success
      end
    end

    describe 'POST #create' do
      context 'with valid params' do
        it 'creates a new Control' do
          expect {
            post :create, params: { profile_id: @profile.id, control: valid_attributes }, session: valid_session
          }.to change(Control, :count).by(1)
        end

        it 'redirects to the created control' do
          post :create, params: { profile_id: @profile.id, control: valid_attributes }, session: valid_session
          expect(response).to redirect_to(@profile)
        end
      end

      context 'with invalid params' do
        it "returns a success response (i.e. to display the 'new' template)" do
          post :create, params: { profile_id: @profile.id, control: invalid_attributes }, session: valid_session
          expect(response).to redirect_to(@profile)
        end
      end
    end

    describe 'PUT #update' do
      context 'with valid params' do
        let(:new_attributes) {
          FactoryBot.build(:control2).attributes
        }

        it 'updates the requested control' do
          control = create :control, profile_id: @profile.id, created_by: user
          title = control.title
          put :update, params: { profile_id: control.profile_id, id: control.to_param, control: new_attributes }, session: valid_session
          control.reload
          expect(control.title).to_not eq(title)
        end

        it 'redirects to the control' do
          control = create :control, profile_id: @profile.id, created_by: user
          put :update, params: { profile_id: control.profile_id, id: control.to_param, control: valid_attributes }, session: valid_session
          expect(response).to redirect_to(profile_control_url(control.profile, control))
        end
      end

      context 'with invalid params' do
        it "returns a success response (i.e. to display the 'edit' template)" do
          control = create :control, profile_id: @profile.id, created_by: user
          put :update, params: { profile_id: control.profile_id, id: control.to_param, control: invalid_attributes }, session: valid_session
          expect(response).to be_success
          expect(response).to render_template(:edit)
        end
      end
    end

    describe 'DELETE #destroy' do
      it 'destroys the requested control' do
        control = create :control, profile_id: @profile.id, created_by: user
        expect {
          delete :destroy, params: { profile_id: control.profile_id, id: control.to_param }, session: valid_session
        }.to change(Control, :count).by(-1)
      end

      it 'redirects to the controls list' do
        control = create :control, profile_id: @profile.id, created_by: user
        delete :destroy, params: { profile_id: control.profile_id, id: control.to_param }, session: valid_session
        expect(response).to redirect_to(control.profile)
      end
    end
  end
end
