require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe ControlsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Control. As you add validations to Control, be sure to
  # adjust the attributes here as well.

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ControlsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  context 'Editor is logged in' do
    let(:user) { FactoryBot.create(:editor) }
    let(:valid_attributes) {
      FactoryBot.build(:profile).attributes
    }

    before do
      db_sign_in user
    end

    before(:each) do
      @evaluation = create :evaluation, created_by: user
      valid_attributes['created_by'] = user
      @profile = @evaluation.profiles.create! valid_attributes
    end

    describe 'GET #show' do
      it 'returns a success response' do
        control = create :control, profile_id: @profile.id
        get :show, params: { profile_id: @profile.id, id: control.to_param }, session: valid_session
        expect(response).to be_successful
      end
    end

    describe 'GET #details' do
      it 'returns a success response' do
        control = create :control, profile_id: @profile.id
        get :details, format: 'js', params: { profile_id: control.profile_id, id: control.to_param, evaluation_id: @evaluation.id }, xhr: true, session: valid_session
        expect(response.content_type).to eq('text/javascript')
      end
    end

  end
end
