require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe EvaluationsController, type: :controller do

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EvaluationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  context 'Editor is logged in' do
    let(:user) { FactoryGirl.create(:editor) }
    before do
      sign_in user
    end

    describe "GET #index" do
      it "returns a success response" do
        evaluation = create :evaluation, created_by: user
        get :index, params: {}, session: valid_session
        expect(response).to be_success
      end
    end

    describe "GET #show" do
      it "returns a success response" do
        evaluation = create :evaluation, created_by: user
        get :show, params: {id: evaluation.to_param}, session: valid_session
        expect(response).to be_success
      end
    end

    describe "GET #ssp" do
      it "returns a success response" do
        evaluation = create :evaluation, created_by: user
        get :ssp, params: {id: evaluation.to_param}, session: valid_session
        expect(response).to be_success
      end
    end

    describe "GET #nist_800_53" do
      it "returns a success response" do
        evaluation = create :evaluation, created_by: user
        get :nist_800_53, params: {id: evaluation.to_param, category: "Medium"}, session: valid_session
        expect(response.content_type).to eq("application/json")
      end
    end

    describe "POST #upload" do
      it "can upload an evaluation" do
        @file = fixture_file_upload('sample_jsons/good_nginxresults.json', 'text/json')
        post :upload, params: {:file => @file}, session: valid_session
        expect(response).to redirect_to(Evaluation.last)
      end
    end

    describe "DELETE #destroy" do
      it "is blocked from destroying the evaluation it doesn't own" do
        evaluation = create :evaluation
        expect {
          delete :destroy, params: {id: evaluation.to_param}, session: valid_session
        }.to raise_error(CanCan::AccessDenied)
      end

      it "destroys the owned evaluation" do
        evaluation = create :evaluation, created_by: user
        expect {
          delete :destroy, params: {id: evaluation.to_param}, session: valid_session
        }.to change(Evaluation, :count).by(-1)
      end

      it "redirects to the evaluation list" do
        evaluation = create :evaluation, created_by: user
        delete :destroy, params: {id: evaluation.to_param}, session: valid_session
        expect(response).to redirect_to(evaluations_url)
      end

    end
  end

  context 'An Admin is logged in' do
    let(:admin) { FactoryGirl.create(:admin) }
    before do
      sign_in admin
    end

    describe "DELETE #destroy" do
      it "destroys the requested evaluation" do
        evaluation = create :evaluation
        expect {
          delete :destroy, params: {id: evaluation.to_param}, session: valid_session
        }.to change(Evaluation, :count).by(-1)
      end
    end

    it "redirects to the evaluations list" do
      evaluation = create :evaluation
      delete :destroy, params: {id: evaluation.to_param}, session: valid_session
      expect(response).to redirect_to(evaluations_url)
    end

  end
end
