require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe GroupsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Group. As you add validations to Group, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryBot.build(:group).attributes
  }

  let(:invalid_attributes) {
    { title: 'MyString2', controls: 'MyString2', control_id: 'MyString2' }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GroupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  context 'Editor is logged in' do
    let(:user) { FactoryBot.create(:editor) }
    before do
      db_sign_in user
    end

    before(:each) do
      @profile = create :profile, created_by: user
    end

    describe 'GET #show' do
      it 'returns a success response' do
        group = @profile.groups.create! valid_attributes
        get :show, params: { profile_id: @profile.id, id: group.to_param }, session: valid_session
        expect(response).to be_success
      end
    end

    describe 'GET #new' do
      it 'returns a success response' do
        get :new, params: { profile_id: @profile.id }, session: valid_session
        expect(response).to be_success
      end
    end

    describe 'POST #create' do
      context 'with valid params' do
        it 'creates a new Group' do
          expect {
            post :create, params: { profile_id: @profile.id, group: valid_attributes }, session: valid_session
          }.to change { @profile.reload.groups.count }.by(1)
        end

        it 'redirects to the created group' do
          post :create, params: { profile_id: @profile.id, group: valid_attributes }, session: valid_session
          expect(response).to redirect_to(profile_group_url(@profile, @profile.reload.groups.last))
        end
      end

      context 'with invalid params' do
        it "returns a success response (i.e. to display the 'new' template)" do
          post :create, params: { profile_id: @profile.id, group: invalid_attributes }, session: valid_session
          expect(response).to redirect_to(@profile)
        end
      end
    end

    describe 'PUT #update' do
      context 'with valid params' do
        let(:new_attributes) {
          FactoryBot.build(:group2).attributes
        }

        it 'updates the requested group' do
          group = @profile.groups.create! valid_attributes
          title = group.title
          put :update, params: { profile_id: @profile.id, id: group.to_param, group: new_attributes }, session: valid_session
          group.reload
          expect(group.title).to_not eq(title)
        end

        it 'redirects to the group' do
          group = @profile.groups.create! valid_attributes
          put :update, params: { profile_id: @profile.id, id: group.to_param, group: valid_attributes }, session: valid_session
          expect(response).to redirect_to(profile_group_url(@profile, @profile.reload.groups.last))
        end
      end

      context 'with invalid params' do
        it 'should raise' do
          group = @profile.groups.create! valid_attributes
          put :update, params: { profile_id: @profile.id, id: group.to_param, group: invalid_attributes }, session: valid_session
          expect(response).to redirect_to(profile_group_url(@profile, group))
          expect(response).to_not be_success
        end
      end
    end

    describe 'PUT #add' do
      context 'with valid params' do
        let(:new_attributes) {
          FactoryBot.build(:group2).attributes
        }

        it 'updates the requested group' do
          group = @profile.groups.create! valid_attributes
          controls = group.controls
          put :add, params: { profile_id: @profile.id, id: group.to_param, group: new_attributes }, session: valid_session
          group.reload
          expect(group.controls).to_not eq(controls)
        end

        it 'redirects to the group' do
          group = @profile.groups.create! valid_attributes
          put :add, params: { profile_id: @profile.id, id: group.to_param, group: valid_attributes }, session: valid_session
          expect(response).to redirect_to(profile_group_url(@profile, @profile.reload.groups.last))
        end
      end
    end

    describe 'PUT #remove' do
      context 'with valid params' do
        it 'updates the requested group' do
          group = @profile.groups.create! valid_attributes
          controls = group.controls
          put :remove, params: { profile_id: @profile.id, id: group.to_param, control_id: group.controls.first }, session: valid_session
          group.reload
          expect(group.controls).to_not eq(controls)
        end

        it 'redirects to the group' do
          group = @profile.groups.create! valid_attributes
          put :remove, params: { profile_id: @profile.id, id: group.to_param, control_id: group.controls.first }, session: valid_session
          expect(response).to redirect_to(profile_group_url(@profile, @profile.reload.groups.last))
        end
      end
    end

    describe 'DELETE #destroy' do
      it 'destroys the requested group' do
        group = @profile.groups.create! valid_attributes
        expect {
          delete :destroy, params: { profile_id: @profile.id, id: group.to_param }, session: valid_session
        }.to change { @profile.reload.groups.count }.by(-1)
      end

      it 'redirects to the groups list' do
        group = @profile.groups.create! valid_attributes
        delete :destroy, params: { profile_id: @profile.id, id: group.to_param }, session: valid_session
        expect(response).to redirect_to(@profile)
      end
    end
  end
end
