require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe ProfileAttributesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ProfileAttribute. As you add validations to ProfileAttribute, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryBot.build(:profile_attribute).attributes
  }

  let(:invalid_attributes) {
    { name: nil, option_description: 'MyString2', option_default: ['MyString2'] }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProfileAttributesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  context 'Editor is logged in' do
    let(:user) { FactoryBot.create(:editor) }
    before do
      db_sign_in user
    end

    before(:each) do
      @profile = create :profile, created_by: user
    end

    describe 'GET #show' do
      it 'returns a success response' do
        profile_attribute = @profile.profile_attributes.create! valid_attributes
        get :show, params: { profile_id: @profile.id, id: profile_attribute.to_param }, session: valid_session
        expect(response).to be_success
      end
    end

    describe 'GET #new' do
      it 'returns a success response' do
        get :new, params: { profile_id: @profile.id }, session: valid_session
        expect(response).to be_success
      end
    end

    describe 'GET #edit' do
      it 'returns a success response' do
        profile_attribute = @profile.profile_attributes.create! valid_attributes
        get :edit, params: { profile_id: @profile.id, id: profile_attribute.to_param }, session: valid_session
        expect(response).to be_success
      end
    end

    describe 'POST #create' do
      context 'with valid params' do
        it 'creates a new ProfileAttribute' do
          expect {
            post :create, params: { profile_id: @profile.id, profile_attribute: valid_attributes }, session: valid_session
          }.to change { @profile.reload.profile_attributes.count }.by(1)
        end

        it 'redirects to the created profile_attribute' do
          post :create, params: { profile_id: @profile.id, profile_attribute: valid_attributes }, session: valid_session
          expect(response).to redirect_to(edit_profile_url(@profile))
        end
      end

      context 'with invalid params' do
        it 'returns a success response' do
          post :create, params: { profile_id: @profile.id, profile_attribute: invalid_attributes }, session: valid_session
          expect(response).to_not be_success
          expect(response).to redirect_to(edit_profile_url(@profile))
        end
      end
    end

    describe 'PUT #update' do
      context 'with valid params' do
        let(:new_attributes) {
          { name: 'MyString2', option_description: 'MyString2', option_default: ['MyString2'] }
        }

        it 'updates the requested profile_attribute' do
          profile_attribute = @profile.profile_attributes.create! valid_attributes
          name = profile_attribute.name
          put :update, params: { profile_id: @profile.id, id: profile_attribute.to_param, profile_attribute: new_attributes }, session: valid_session
          profile_attribute.reload
          expect(profile_attribute.name).to_not eq(name)
        end

        it 'redirects to the profile_attribute' do
          profile_attribute = @profile.profile_attributes.create! valid_attributes
          put :update, params: { profile_id: @profile.id, id: profile_attribute.to_param, profile_attribute: valid_attributes }, session: valid_session
          expect(response).to redirect_to(edit_profile_url(@profile))
        end
      end

      context 'with invalid params' do
        it "returns a success response (i.e. to display the 'edit' template)" do
          profile_attribute = @profile.profile_attributes.create! valid_attributes
          put :update, params: { profile_id: @profile.id, id: profile_attribute.to_param, profile_attribute: invalid_attributes }, session: valid_session
          expect(response).to be_success
          expect(response).to render_template(:edit)
        end
      end
    end

    describe 'DELETE #destroy' do
      it 'destroys the requested profile_attribute' do
        profile_attribute = @profile.profile_attributes.create! valid_attributes
        expect {
          delete :destroy, params: { profile_id: @profile.id, id: profile_attribute.to_param }, session: valid_session
        }.to change { @profile.reload.profile_attributes.count }.by(-1)
      end

      it 'redirects to the profile_attributes list' do
        profile_attribute = @profile.profile_attributes.create! valid_attributes
        delete :destroy, params: { profile_id: @profile.id, id: profile_attribute.to_param }, session: valid_session
        expect(response).to redirect_to(edit_profile_url(@profile))
      end
    end
  end
end
